{
    "name": "Realestate",
    "summary": "Manage rental properties, tenants, contracts, and rent invoices",
    "description": """Integrated real estate operations for Odoo Community.""",
    "author": "CodeSudio",
    "category": "Industries/Real Estate",
    "version": "17.0.1.1.0",
    "license": "LGPL-3",
    "images": ["static/description/icon.png"],
    "depends": ["base", "mail", "contacts", "product", "account"],
    "data": [
        "security/realestate_security.xml",
        "security/ir.model.access.csv",
        "data/res_currency_data.xml",
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
        "views/property_views.xml",
        "views/tenant_views.xml",
        "views/contract_views.xml",
        "views/account_move_views.xml",
        "views/res_config_settings_views.xml",
        "views/menus.xml",
    ],
    "demo": ["demo/realestate_demo.xml"],
    "application": True,
    "installable": True,
}
