from . import property
from . import partner
from . import contract
from . import contract_renewal_wizard
from . import dashboard
from . import account_move
from . import res_company
from . import financial_report
from . import report_export_wizard
